apiVersion: v1
kind: ServiceAccount
metadata:
  name: fillaiq-web
  namespace: {{ .Values.namespacePrefix }}-{{ .Values.environment }}
  labels:
    app: fillaiq
    component: web
    environment: {{ .Values.environment }}
automountServiceAccountToken: true
